g=int(input("Ingresa el grado de semestre que te encuentras cursando"))
if g==1:
	print("")
	print("Las materias que estas cursando son:")
	print("Calculo diferencial")
	print("Fundamentos de Programcion")
	print("Matematicas discretas I")
	print("Introduccion a las tics")
	print("Taller de etica")
	print("Fundamentos de investigacion")
	print("Los creditos del semestre son 26")
elif g==2:
	print("")
	print("Las materias que estas cursando son:")
	print("Calculo integral")
	print("Programacion orientada a objetos")
	print("Matematicas discretas II")
	print("Probabilidad y estadistica")
	print("Contabilidad y costos")
	print("Los creditos del semestre son 25")
elif g==3:
	print("")
	print("Las materias que estas cursando son:")
	print("Matematicas aplicadas a comunicaciones")
	print("Estructura y organizacion de datos")
	print("Administracion gerencial")
	print("Fundamentos de bases de datos")
	print("Electricidad y magnetismo")
	print("Algebra lineal")
	print("Los creditos del semestre son 27")
elif g==4:
	print("")
	print("Las materias que estas cursando son:")
	print("Analisis de señales y sistemas")
	print("Programacion II")
	print("Matematicas para la toma de decisiones")
	print("Taller de bases de datos")
	print("Circuitos electricos y electronicos")
	print("Ingenieria de software")
	print("Los creditos del semestre son 28")
elif g==5:
	print("")
	print("Las materias que estas cursando son:")
	print("Fundamentos de redes")
	print("Telecomunicaciones")
	print("Administracion de proyectos")
	print("Bases de datos distribuidas")
	print("Arquitectura de computadoras")
	print("Taller de ingenieria de software")
	print("Los creditos del semestre son 28")
elif g==6:
	print("")
	print("Las materias que estas cursando son:")
	print("Redes de computadoras")
	print("Programacion web")
	print("Desarrollo de emprendedores")
	print("Taller de investigacion I")
	print("Sistemas operativos I")
	print("Tecnologias inalambricas")
	print("Los creditos del semestre son 27")
elif g==7:
	print("")
	print("Las materias que estas cursando son:")
	print("Redes emergentes")
	print("Desarrollo de aplicaciones para Dips. M")
	print("Desarrollo Sustentable")
	print("Taller de investigacion II")
	print("Sistemas operativos II")
	print("Negocios electronicos I")
	print("Los creditos del semestre son 28")
elif g==8:
	print("")
	print("Las materias que estas cursando son:")
	print("Administracion y seguridad de redes")
	print("Auditoria en tecnologias de la informacion")
	print("Interaccion humano computadora")
	print("Ingenieria del conocimiento")
	print("Negocios electronicos II")
	print("Los creditos del semestre son 21")
elif g==9:
	print("")
	print("Las materias que estas cursando son:")
	print("Especialidad")
	print("Residencias profesionales")
	print("Servicio social")
	print("Actividades complementarias")
	print("Los creditos del semestre son 50")
elif (g>9):
	print("Ahora eres Ingeniero en tics")
